apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kubernetes
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/AswinT22/flux-cd-demo
